source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-relative-links"
  gem "jekyll-github-metadata"
end

# For local testing on Ruby 3.0+
gem "webrick", "~> 1.8"
